import "./globals.css"
import type { Metadata } from "next"
import { getSession } from "@/lib/nextauth"
import { Toaster } from "@/components/ui/sonner"
import { Chakra_Petch } from "next/font/google"
import AuthProvider from "@/components/providers/auth-provider"
import { ThemeProvider } from "@/components/providers/theme-provider"
import { TooltipProvider } from "@/components/animate-ui/components/animate/tooltip"

const chakraPatch = Chakra_Petch({
	subsets: ["latin"],
	weight : ["300","400","500","600","700"],
	display: "swap",
	variable : "--font-chakra-petch"
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
	const session = await getSession()
	return (
		<html suppressHydrationWarning>
			<body className={`${chakraPatch.variable} font-chakra`}>
				<AuthProvider session={session}>
					<ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
						<TooltipProvider>
							{children}
						</TooltipProvider>
						<Toaster />
					</ThemeProvider>
				</AuthProvider>
			</body>
		</html>
	)
}
